### ISSUE TITLE
AttributeError: 'SystemEnclosureContainedElement' object has no attribute 'type'

### ISSUE THREAD

**Issue by logg-sar** [biosbits/bits#1]
Hi there

i get this error message while booting from an usb hard drive:

BIOS Implementation Test Suite (BITS)
bits-2005, build ID 6026f6460fee9dff3897191a2b972c9536f23e53
Initialization redirect module done
Importing acpi module... done
Initializing serial port redirection module...
Initialization serial port redirection module done
Importing os module... done
Importing bitsconfig module... done
Initializing bitsconfig module... done
Importing grubcmds module... done
Initializing grubcmds module... done
Importing bits module... done
Initializing PCI Express MCFG detection module...
Initialization PCI Express MCFG detection module done
Importing readline module... done
Initializing readline module... done
Importing rlcompleter_extra module... done
Importing testacpi module... done
Initializing testacpi module... done
Importing testsmrr module... done
Importing smilatency module... done
Initializing smilatency module... done
Importing mptable module... done
Initializing mptable module... done
Importing cpulib module... done
Initializing cpulib module... done
Importing testsuite module... done
Initializing testsuite module... done
Importing sysinfo module... done
Initializing sysinfo module...
Processor signature 0x306c3, detected CPU as Unknown
Initialization sysinfo module done
Importing smbios module... done
Initializing smbios module...
Error parsing SystemEnclosure
Traceback (most recent call last):
  File "/boot/python/smbios.py", line 364, in **init**
    self.add_field('contained_elements', tuple(SystemEnclosureContainedElement(u, self.contained_element_length) for i in range(self.contained_element_count)))
  File "/boot/python/smbios.py", line 364, in <genexpr>
    self.add_field('contained_elements', tuple(SystemEnclosureContainedElement(u, self.contained_element_length) for i in range(self.contained_element_count)))
  File "/boot/python/smbios.py", line 386, in **init**
    self.add_field('type_select', bitfields.getbits(self.type, 7), unpack.format_table("contained_element_type[7]={}", type_selections))
AttributeError: 'SystemEnclosureContainedElement' object has no attribute 'type'
SMBIOS information:
0: BIOSInformation(type=0x0, length=0x18, handle=0x0, vendor=1 'FUJITSU //
  American Megatrends Inc.', version=2 'V4.6.5.4 R2.14.0 for D3239-A1x',
  starting_address_segment=0xf000, release_date=3 '04/16/2015',
  rom_size=0x7f, characteristics=0x134099880, characteristics_extensions=[3,
  13], major_release=0x2, minor_release=0xe, ec_major_release=0xff,
  ec_minor_release=0xff)
1: SystemInformation(type=0x1, length=0x1b, handle=0x1, manufacturer=1
  'FUJITSU', product_name=2 'PRIMERGY TX1320 M1', version=3 'GS01',
  serial_number=4 'YLXL001001', uuid=UUID('c9b50cb1-4c16-8a4f-b86e-
  642761e128e4'), wakeup_type=6 (Power Switch), sku_number=5
  'ABN:1386-V101-101', family=6 'SERVER')
Initialization smbios module done
Importing cpumenu module... done
Initializing cpumenu module... done
Importing bootmenu module... done
Initializing bootmenu module... done
Importing mwaitmenu module... done
Initializing mwaitmenu module... done
Importing builtin module... done
Error parsing SystemEnclosure
Traceback (most recent call last):
  File "/boot/python/smbios.py", line 364, in **init**
    self.add_field('contained_elements', tuple(SystemEnclosureContainedElement(u, self.contained_element_length) for i in range(self.contained_element_count)))
  File "/boot/python/smbios.py", line 364, in <genexpr>
    self.add_field('contained_elements', tuple(SystemEnclosureContainedElement(u, self.contained_element_length) for i in range(self.contained_element_count)))
  File "/boot/python/smbios.py", line 386, in **init**
    self.add_field('type_select', bitfields.getbits(self.type, 7), unpack.format_table("contained_element_type[7]={}", type_selections))
AttributeError: 'SystemEnclosureContainedElement' object has no attribute 'type'

Can you help me with this?

**Comment by joshtriplett** [comment]
Thanks for reporting this issue, and for including the log, which made this easy to find and fix.  Commit cafd10f43799cb06397f6c157ee9bd4c80896015 should fix this issue.  The next release of BITS will include that fix, or you can build the current version from git if you need it sooner.
